allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  canvas: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
